# Config Base
# This is where root config key goes.
# ###################################
title: Sport Med Lab
baseURL: 
enableRobotsTXT: true
disableAliases: true
staticDir: static


build:
  writeStats: true

DefaultContentLanguage: gr

languages:
  gr:
    languageName: "Ελληνικά"
    weight: 10
  en:
    languageName: English
    weight: 20