mounts:
  - source: assets
    target: assets
  - source: static
    target: static
  - source: node_modules
    target: static/plugins
imports:
  - path: github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3