mounts:
  - source: assets
    target: assets
  - source: _huge
    target: assets/_huge
imports:
  - path: github.com/theNewDynamic/huge
  - path: github.com/gohugoio/hugo-mod-jslibs-dist/alpinejs/v3