[build]
publish = "public"
command = "hugo"

[build.environment]
  GO_VERSION = "1.14"
  HUGO_VERSION = "0.110"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"