# https://github.com/theNewDynamic/huge/wiki/Fonts
fonts:
- family: Open
  file: fonts/open-sans-v27-latin-regular
  weight: 400
- family: Open
  file: fonts/open-sans-v27-latin-italic
  weight: 400
  style: italic
- family: Open
  file: fonts/open-sans-v27-latin-700
  weight: 700
  style: normal
- family: Open
  file: fonts/open-sans-v27-latin-800
  weight: 800
  style: normal